language: python
python: 3.6
script:
- python setup.py test
- pytest
deploy:
  provider: pypi
  user: TedPetrou
  password:
    secure: jKb6fLEpzK4gjKdnfQgngk9sxRdx2Z/pzrw3tOHdDu/Q7rKqfYCuMXlOJYOf51dO+T5A09/iy2xH0IE/70HSmS+qUIOGA3Z0NpvYvjlH1H9/Zpl/98lAiPwEePKw3PWUwSJJprn57st1JThR6rzDtJOmxA342YwpE/25SL4NXJYr7O8X+BCUAxJE5T/LC9VmVGtNfQEM8lPM0KhL5uzeJsRn4L56jYu0GcfdAOcVNPUb7jNTf9H0B2N3zvLAUieYCbwB7NHyf+vzCKuRXaN3cvGvVEEhBOpp8RqgHdFeK03OravSlSER8OP/gzXDzPgg+0AMD7hKQsw1smTrdH0uas6bTO6w/Cb/jyhANxgc+Z4AbcNb025r6jl3X00bFWhLTdo41A6dVB6tuQMZMALa+6glGx7f29hCPXbE4DiErOVPRDddnpK5yItv9nDg7CyDz76Rxn4cOtAkkEmsG32L3wdsy5faZqpMixF+CZMammeVdcV3Hnn4cPDKECWodCdBN0ZqP14H52jn1SAdHzZy2OPNve8aSAGiSyYdrlU1dkNqkpnKr/3wsn1m7EFX97X4YddKJWUXGX4ufVmL58jpFJGsAmUgRjYJr7ne1SfMe0XwjpWeYv46OK3R1uyMXrDGrDEzanxmhWCu5HQe3DYZOBVFM8IQwirY3RL2JDlRbaU=
  distributions: sdist bdist_wheel
